### ISSUE TITLE
Reshaping does not work

### ISSUE THREAD

**Issue by poyynt** [alihoseiny/word_cloud_fa#2]
**Describe the bug**
It is expected to reshape the words that appear in the Word Cloud, but words appear unreshaped and wrong-looking.

**To Reproduce**
Python 3.8, wordcloud_fa v0.1.5, arabic_reshaper v2.0.15 on macOS v10.15.3
Input: any persian text

**Expected behavior**
A good cloud as in the project README.

**Screenshots**
![telegram-cloud-photo-size-4-5960644511078133959-y](https://user-images.githubusercontent.com/28945566/75394231-f1d17a00-5904-11ea-8009-0a1200c48a48.jpg)

**Code**
```wc = WordCloudFa(
            width=900, height=900,
            background_color="white",
            font_path="assets/fonts/font2.ttf",
            mask = mask_array,
            persian_normalize=True,
            include_numbers=False,
        )

        word_cloud = wc.generate(text)
```

**Comment by alihoseiny** [comment]
Thank for your report. Please remove your package and install the new version released today. 
I hope that solves your problem. Please notify me after testing the new version.
Regards.
