### ISSUE TITLE
incompatibility with wordcloud >1.7.0

### ISSUE THREAD

**Issue by habilg** [alihoseiny/word_cloud_fa#20]
hi friends,
As you may know, your paramount package requires wordcloud 1.7.0 as its dependency. unfortunately, this package is not installed on python>=3.9. Do you have any suggestions other than changing the py version?

**Comment by alihoseiny** [comment]
Hi.
We will release the new version in the following days and this problem will be solved.

**Comment by alihoseiny** [comment]
You can try the new version now. Feel free to create a new issue if you have any other problems.
