### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kian79** [alihoseiny/word_cloud_fa#3]
**Describe the bug**
For some texts code doesn't work and after few seconds it throws following exception.
AssertionError: LRI not allowed here
But when I write "no_reshape=True" in constructor the problem fixes but words appear unreshaped again like previous version.   

**To Reproduce**
python 3,wordcloud-fa v0.1.6 on ubuntu v18.04
input: some persian texts.

**Expected behavior**
A good cloud like in the project README.

**Comment by kian79** [comment]
I fixed it by removing some weird chars from text by the i found at [](https://stackoverflow.com/questions/49362300/word-cloud-arabic)

**Comment by alihoseiny** [comment]
I am so happy that your problem has been solved. But could you please send those characters for preventing the same error for other users?
I think there is a problem in arabic-reshaper module. But I should check it out.

**Comment by kian79** [comment]
Unfortunately I couldn't figure out which characters caused the problem.
But I used this code to remove them.

```
def removeWeirdChars(text):
    weridPatterns = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               u"\U0001f926-\U0001f937"
                               u'\U00010000-\U0010ffff'
                               u"\u200d"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\u3030"
                               u"\ufe0f"
                               u"\u2069"
                               u"\u2066"
                               u"\u200c"
                               u"\u2068"
                               u"\u2067"
                               "]+", flags=re.UNICODE)
    return weridPatterns.sub(r'', text)

```

**Comment by alihoseiny** [comment]
Thank you a lot. I will consider this in the next release.
